import { Geist, Geist_Mono, Krona_One } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Shared/Navbar";
import ClientToaster from "@/components/libs/ClientToaster";
import Footer from "@/components/Shared/Footer";
import { CursorProvider } from "@/components/libs/Context/CursorContext";
import AnimatedCursor from "@/components/libs/AnimatedCursor";

const kronaOne = Krona_One({
  weight: ["400"], // Krona One only has one weight: Regular 400
  subsets: ["latin"], // Specify the necessary subsets
  display: "swap", // 'swap' ensures text is visible with a fallback font while the custom font loads
  variable: "--font-krona-one", // Optional: for use with CSS variables
});

export const metadata = {
  title: "Adrien Ticket",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${kronaOne.className}`}>
      <body>
        <CursorProvider>
          <ClientToaster />
          <AnimatedCursor borderColor="white" />
          <Navbar />
          {children}
          <Footer />
        </CursorProvider>
      </body>
    </html>
  );
}
